spring:
  profiles:
    active: dev
  application:
    name: smartshop

server:
  port: ${SERVER_PORT}
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT}

app:
  vat:
    rate: ${DEFAULT_VAT_RATE}
  loyalty:
    tiers:
      silver:
        min-orders: 3
        min-amount: 1000.0
        discount: 5.0
        min-subtotal: 500.0
      gold:
        min-orders: 10
        min-amount: 5000.0
        discount: 10.0
        min-subtotal: 800.0
      platinum:
        min-orders: 20
        min-amount: 15000.0
        discount: 15.0
        min-subtotal: 1200.0
  payment:
    cash:
      max-amount: 20000.0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always